### ISSUE TITLE
引用的番剧封面图是 http，会显示网站链接不安全，小锁没了~

### ISSUE THREAD

**Issue by AnimatorBullet** [TaylorLottner/bilibili#1]
SSL已开，但是尝试后https也是能打开图片的~~

**Comment by TaylorLottner** [comment]
emmmn，这.....




| |
🎉梨花町の腎兄さん🎉
|
|
邮箱：emaillmr@163.com
|

签名由 网易邮箱大师 定制

在2020年03月12日 00:15，Bullet.S 写道：

SSL已开，但是尝试后https也是能打开图片的~~

**Comment by AnimatorBullet** [comment]
哈哈我尝试解决了下，但是不懂php，能力有限~~

**Comment by TaylorLottner** [comment]
此为您网站的设置错误，经过5个网友的测试，均显示连接安全，您可以检查是否有不对的地方，下载一个ssl修复插件修复一下

**Comment by AnimatorBullet** [comment]
> 此为您网站的设置错误，经过5个网友的测试，均显示连接安全，您可以检查是否有不对的地方，下载一个ssl修复插件修复一下

这样啊，好吧，可是其他所有连接都是https，F12里面看封面图引用都是http，不过算了也不折腾了~

**Comment by TaylorLottner** [comment]
不过一般不会出现这种情况，中午我看一下我的网站引用，(●'◡'●)是不是http的。。。嘿嘿
